# Generated by Django 5.0.3 on 2024-03-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('a', 'student'), ('b', 'teacher')], max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('modules', models.CharField(max_length=30)),
            ],
        ),
    ]
